### ISSUE TITLE
Troubleshooting guide should be a comprehensive checklist that we trust

### ISSUE THREAD

**Issue by okdistribute** [getditto/docs#447]
When a customer comes with an issue, we should be able to run through the troubleshooting checklist very clearly. Right now, it's a list of potential problems and it is generally useful, but it is woefully incomplete.

- [x] Read previous customer debugging sessions and identify common issues
- [x] Reorganize the troubleshooting guide to build from the most basic, common problems to more obscure issues
- [x] Read known bugs (labeled 'bug') in the Ditto repository and create troubleshooting items for each bug that define how to identify the issue, and how to work around it.
- [x] Add a customer engineering policy to always use the troubleshooting guide before raising the issue internally as a new problem
